// consoles/shared/admin/src/components/OperationRecovery.vue
<script
  setup
  lang="ts"
  generic="
    T extends {
      id: string;
      state: 'COMMITTED' | 'PROCESSING' | 'NOT_COMMITTED' | 'UNKNOWN';
      createdAt: Date;
      canReplay: boolean;
    }
  "
>
import { onScopeDispose, ref, shallowRef, toRaw } from 'vue';
import { ElButton, ElCard, ElTable, ElTableColumn, ElTag } from 'element-plus';
import type { ConsoleApiResult } from '@saas-forge/app-runtime';
import { computed } from 'vue';
import { createTranslator } from '@saas-forge/i18n';
import { recoveryMessages } from '../messages/recovery';
import { useConsole } from '../runtime/context';
import Problem from './Problem.vue';
const props = withDefaults(
  defineProps<{
    kind?: 'creation' | 'plan' | 'quota' | 'subscription';
    load: (input: {
      cursor?: string;
      signal: AbortSignal;
    }) => Promise<
      ConsoleApiResult<{ items: readonly T[]; hasMore: boolean; nextCursor: string | null }>
    >;
    replay: (operation: T, signal: AbortSignal) => Promise<ConsoleApiResult<T>>;
    label: (operation: T) => string;
    resourceId: (operation: T) => string | null | undefined;
  }>(),
  { kind: 'creation' },
);
const emit = defineEmits<{ view: [id: string] }>();
const { locale } = useConsole();
const translator = computed(() =>
  createTranslator({
    namespace: '@saas-forge/admin/recovery',
    locale: locale.value,
    messages: recoveryMessages,
  }),
);
const t = (key: keyof (typeof recoveryMessages)['zh-CN']) => translator.value.translate(key);
const rows = shallowRef<readonly T[]>();
const nextCursor = ref<string | null>(null);
const cursors = ref<(string | undefined)[]>([undefined]);
const busy = ref(false);
const problem = ref<string>();
let controller: AbortController | undefined;
onScopeDispose(() => controller?.abort());
const operationText = (row: T) => {
  const value = props.label(row);
  return (props.kind === 'plan' || props.kind === 'quota') &&
    (value === 'CREATE' || value === 'ACTIVATE')
    ? t(`${props.kind}Recovery${value === 'CREATE' ? 'Create' : 'Activate'}`)
    : value;
};
const stateText = (state: T['state']) => t(`creationRecovery${state}`);
const text = (suffix: 'Title' | 'Read' | 'Continue' | 'View' | 'Empty' | 'Previous' | 'Next') =>
  t(`${props.kind}Recovery${suffix}`);
async function read(next = cursors.value) {
  if (busy.value) return;
  controller = new AbortController();
  busy.value = true;
  problem.value = undefined;
  try {
    const result = await props.load({ cursor: next.at(-1), signal: controller.signal });
    if (controller.signal.aborted) return;
    if (result.ok) {
      rows.value = result.value.items;
      cursors.value = next;
      nextCursor.value = result.value.hasMore ? result.value.nextCursor : null;
      if (result.value.hasMore && !result.value.nextCursor)
        problem.value = 'INVALID_SERVICE_RESPONSE';
    } else problem.value = result.problem.code;
  } catch {
    if (!controller.signal.aborted) problem.value = 'NETWORK_UNAVAILABLE';
  } finally {
    if (!controller.signal.aborted) {
      busy.value = false;
      controller = undefined;
    }
  }
}
async function recover(row: T) {
  if (busy.value || row.state !== 'NOT_COMMITTED' || !row.canReplay) return;
  controller = new AbortController();
  busy.value = true;
  problem.value = undefined;
  let committedId: string | null | undefined;
  try {
    const result = await props.replay(toRaw(row), controller.signal);
    if (controller.signal.aborted) return;
    if (!result.ok) {
      problem.value = result.problem.code;
      return;
    }
    if (result.value.state === 'COMMITTED') committedId = props.resourceId(result.value);
  } catch {
    if (!controller.signal.aborted) problem.value = 'NETWORK_UNAVAILABLE';
    return;
  } finally {
    if (!controller.signal.aborted) {
      busy.value = false;
      controller = undefined;
    }
  }
  if (committedId) emit('view', committedId);
  else await read();
}
</script>
<template>
  <ElCard shadow="never">
    <template #header
      ><div class="flex items-center justify-between gap-16px">
        <h2>{{ text('Title') }}</h2>
        <ElButton :loading="busy" @click="read()">{{ text('Read') }}</ElButton>
      </div></template
    >
    <Problem :code="problem" />
    <p v-if="rows?.length === 0" role="status">{{ text('Empty') }}</p>
    <ElTable v-else-if="rows" :data="[...rows]" row-key="id" :aria-label="text('Title')">
      <ElTableColumn :label="text('Title')"
        ><template #default="{ row }"
          >{{ operationText(row) }} · {{ row.createdAt.toLocaleString(locale) }}</template
        ></ElTableColumn
      >
      <ElTableColumn
        ><template #default="{ row }"
          ><ElTag>{{ stateText(row.state) }}</ElTag></template
        ></ElTableColumn
      >
      <ElTableColumn align="right"
        ><template #default="{ row }"
          ><ElButton
            v-if="row.state === 'COMMITTED' && resourceId(row)"
            :disabled="busy"
            @click="emit('view', resourceId(row)!)"
            >{{ text('View') }}</ElButton
          ><ElButton
            v-else-if="row.state === 'NOT_COMMITTED' && row.canReplay"
            :disabled="busy"
            @click="recover(row)"
            >{{ text('Continue') }}</ElButton
          ></template
        ></ElTableColumn
      >
    </ElTable>
    <div v-if="rows" class="console-actions">
      <ElButton :disabled="busy || cursors.length < 2" @click="read(cursors.slice(0, -1))">{{
        text('Previous')
      }}</ElButton
      ><ElButton :disabled="busy || !nextCursor" @click="read([...cursors, nextCursor!])">{{
        text('Next')
      }}</ElButton>
    </div>
  </ElCard>
</template>

// consoles/shared/react-shell/src/operation-recovery.tsx
import type { ConsoleApiResult } from '@saas-forge/app-runtime';
import { Button, ContentPanel, PersistentError } from '@saas-forge/design-system';
import { createTranslator, type SupportedLocale } from '@saas-forge/i18n';
import { useEffect, useRef, useState } from 'react';
import { shellMessages } from './messages';

interface RecoveryOperation {
  readonly id: string;
  readonly state: 'COMMITTED' | 'PROCESSING' | 'NOT_COMMITTED' | 'UNKNOWN';
  readonly createdAt: Date;
  readonly canReplay: boolean;
}
interface RecoveryPage<T> {
  readonly items: readonly T[];
  readonly nextCursor: string | null;
  readonly hasMore: boolean;
}

/** 读取由 Runtime 管理的原操作者恢复记录；UI 不保存请求或恢复 Key。 */
export function OperationRecoveryPanel<T extends RecoveryOperation>({
  load,
  replay,
  label,
  resourceId,
  quota = false,
  locale,
  onView,
}: {
  readonly load: (input: {
    cursor?: string;
    signal?: AbortSignal;
  }) => Promise<ConsoleApiResult<RecoveryPage<T>>>;
  readonly replay: (operation: T, signal?: AbortSignal) => Promise<ConsoleApiResult<T>>;
  readonly label: (operation: T) => string;
  readonly resourceId: (operation: T) => string | undefined;
  readonly quota?: boolean;
  readonly locale: SupportedLocale;
  readonly onView: (id: string) => void;
}) {
  const translate = createTranslator({
    namespace: '@saas-forge/react-shell',
    locale,
    messages: shellMessages,
  });
  const t = translate.translate.bind(translate);
  const [result, setResult] = useState<ConsoleApiResult<RecoveryPage<T>>>();
  const [busy, setBusy] = useState(false);
  const [problem, setProblem] = useState<string>();
  const [cursors, setCursors] = useState<(string | undefined)[]>([undefined]);
  const request = useRef<AbortController | null>(null);
  useEffect(
    () => () => {
      request.current?.abort();
    },
    [],
  );

  async function read(nextCursors = cursors) {
    request.current?.abort();
    const controller = new AbortController();
    request.current = controller;
    setBusy(true);
    setProblem(undefined);
    const next = await load({
      cursor: nextCursors.at(-1),
      signal: controller.signal,
    });
    if (controller.signal.aborted) return;
    setResult(next);
    setCursors(nextCursors);
    setBusy(false);
  }

  async function recover(operation: T) {
    if (busy) return;
    const controller = new AbortController();
    request.current = controller;
    setBusy(true);
    const next = await replay(operation, controller.signal);
    if (controller.signal.aborted) return;
    const id = next.ok ? resourceId(next.value) : undefined;
    if (next.ok && next.value.state === 'COMMITTED' && id !== undefined) {
      setBusy(false);
      onView(id);
      return;
    }
    setProblem(next.ok ? undefined : next.problem.code);
    setBusy(false);
    if (next.ok) await read();
  }

  return (
    <ContentPanel
      title={t(quota ? 'quotaRecoveryTitle' : 'creationRecoveryTitle')}
      description={t(quota ? 'quotaRecoveryHint' : 'creationRecoveryHint')}
      actions={
        <Button
          disabled={busy}
          onClick={() => {
            void read();
          }}
        >
          {t(quota ? 'quotaRecoveryRead' : 'creationRecoveryRead')}
        </Button>
      }
    >
      {busy ? <p role="status">{t('creationRecoveryPending')}</p> : null}
      {problem !== undefined || result?.ok === false ? (
        <PersistentError title={t(quota ? 'quotaRecoveryFailure' : 'creationRecoveryFailure')}>
          <p>{problem ?? (result?.ok === false ? result.problem.code : '')}</p>
        </PersistentError>
      ) : null}
      {result?.ok ? (
        <>
          {result.value.items.length === 0 ? (
            <p>{t(quota ? 'quotaRecoveryEmpty' : 'creationRecoveryEmpty')}</p>
          ) : (
            <ul>
              {result.value.items.map((operation) => (
                <li key={operation.id}>
                  <strong>{label(operation)}</strong> — {t(`creationRecovery${operation.state}`)}
                  <p>{operation.createdAt.toLocaleString(locale)}</p>
                  {!operation.canReplay &&
                  operation.state !== 'COMMITTED' &&
                  operation.state !== 'PROCESSING' ? (
                    <p>{t(quota ? 'quotaRecoveryUnavailable' : 'creationRecoveryExpired')}</p>
                  ) : null}
                  {operation.state === 'COMMITTED' && resourceId(operation) !== undefined ? (
                    <Button
                      onClick={() => {
                        const id = resourceId(operation);
                        if (id !== undefined) onView(id);
                      }}
                    >
                      {t(quota ? 'quotaRecoveryView' : 'creationRecoveryView')}
                    </Button>
                  ) : null}
                  {operation.state === 'NOT_COMMITTED' && operation.canReplay ? (
                    <Button
                      disabled={busy}
                      onClick={() => {
                        void recover(operation);
                      }}
                    >
                      {t(quota ? 'quotaRecoveryContinue' : 'creationRecoveryContinue')}
                    </Button>
                  ) : null}
                </li>
              ))}
            </ul>
          )}
          <Button
            disabled={busy || cursors.length < 2}
            onClick={() => {
              void read(cursors.slice(0, -1));
            }}
          >
            {t(quota ? 'quotaRecoveryPrevious' : 'creationRecoveryPrevious')}
          </Button>
          <Button
            disabled={busy || !result.value.hasMore}
            onClick={() => {
              if (result.value.nextCursor !== null)
                void read([...cursors, result.value.nextCursor]);
            }}
          >
            {t(quota ? 'quotaRecoveryNext' : 'creationRecoveryNext')}
          </Button>
        </>
      ) : null}
    </ContentPanel>
  );
}
