// consoles/shared/admin/src/application/PasswordSetup.vue
<script setup lang="ts">
import { onScopeDispose, ref } from 'vue';
import { useRouter } from 'vue-router';
import { ElButton, ElForm, ElFormItem, ElInput } from 'element-plus';
import { useConsole, useShellText } from '../runtime/context';
import Problem from '../components/Problem.vue';
const { runtime } = useConsole();
const t = useShellText();
const router = useRouter();
const props = defineProps<{ takeChallenge?: () => string | undefined }>();
let challenge = props.takeChallenge?.();
let controller: AbortController | undefined;
const password = ref('');
const state = ref<'ready' | 'pending' | 'success' | 'unknown' | 'failed'>(
  challenge ? 'ready' : 'failed',
);
const rejected = ref(false);
onScopeDispose(() => {
  controller?.abort();
  challenge = undefined;
  password.value = '';
});
async function submit() {
  if (controller || !challenge) return;
  const token = challenge;
  challenge = undefined;
  const newPassword = password.value;
  password.value = '';
  rejected.value = false;
  state.value = 'pending';
  controller = new AbortController();
  const result = await runtime.establishPassword({ token, newPassword, signal: controller.signal });
  if (controller.signal.aborted) return;
  controller = undefined;
  if (
    !result.ok &&
    result.problem.status === 400 &&
    [
      'PASSWORD_TOO_SHORT',
      'PASSWORD_TOO_LONG',
      'PASSWORD_WHITESPACE_NOT_ALLOWED',
      'PASSWORD_COMPROMISED',
    ].includes(result.problem.code)
  ) {
    challenge = token;
    state.value = 'ready';
    rejected.value = true;
    return;
  }
  state.value = result.ok
    ? 'success'
    : result.problem.status === undefined || result.problem.status >= 500
      ? 'unknown'
      : 'failed';
}
</script>
<template>
  <h1>{{ t('passwordSetupTitle') }}</h1>
  <p v-if="state === 'success'" role="status">{{ t('passwordSetupSuccess') }}</p>
  <Problem
    v-else-if="state === 'unknown' || state === 'failed'"
    :title="t(state === 'unknown' ? 'passwordSetupUnknown' : 'passwordSetupUnavailable')"
  />
  <ElForm v-else label-position="top" @submit.prevent="submit">
    <ElFormItem
      :label="t('newPasswordLabel')"
      :error="rejected ? t('passwordSetupPolicy') : undefined"
    >
      <ElInput
        v-model="password"
        type="password"
        autocomplete="new-password"
        :aria-label="t('newPasswordLabel')"
        :disabled="state === 'pending'"
        required
      />
    </ElFormItem>
    <div class="console-actions">
      <ElButton type="primary" native-type="submit" :loading="state === 'pending'">{{
        t('passwordSetupTitle')
      }}</ElButton>
    </div>
  </ElForm>
  <div class="console-actions">
    <ElButton
      @click="
        challenge = undefined;
        router.replace('/login');
      "
      >{{ t('signIn') }}</ElButton
    >
  </div>
</template>

// consoles/shared/react-shell/src/password-setup.tsx
import type { AuthenticationRuntime } from '@saas-forge/app-runtime';
import {
  Button,
  FormLayout,
  FormRow,
  PageLayout,
  PageTitle,
  PasswordField,
  PersistentError,
  RouteFocusAnnouncement,
  SuccessFeedback,
} from '@saas-forge/design-system';
import { createTranslator } from '@saas-forge/i18n';
import { useEffect, useRef, useState } from 'react';
import { useLocation, useNavigate } from 'react-router';
import { useConsoleLocale } from './console-locale';
import { shellMessages } from './messages';

export function PasswordSetupPage({ runtime }: { readonly runtime: AuthenticationRuntime }) {
  const { locale } = useConsoleLocale();
  const translate = createTranslator({
    namespace: '@saas-forge/react-shell',
    locale,
    messages: shellMessages,
  });
  const location = useLocation();
  const navigate = useNavigate();
  const captured = useRef(false);
  const challenge = useRef<string | undefined>(undefined);
  const request = useRef<AbortController | undefined>(undefined);
  const [valid, setValid] = useState(false);
  const [password, setPassword] = useState('');
  const [passwordRejected, setPasswordRejected] = useState(false);
  const [status, setStatus] = useState<'ready' | 'pending' | 'success' | 'failed' | 'unknown'>(
    'ready',
  );
  useEffect(() => {
    if (captured.current) return;
    captured.current = true;
    const token = new URLSearchParams(location.hash.slice(1)).get('token');
    if (token !== null && /^[A-Za-z0-9_-]{43}$/.test(token)) {
      challenge.current = token;
      setValid(true);
    }
    void navigate('/password-setup', { replace: true });
  }, [location.hash, navigate]);
  useEffect(
    () => () => {
      request.current?.abort();
    },
    [],
  );

  return (
    <PageLayout
      title={
        <>
          <RouteFocusAnnouncement
            routeKey={location.key}
            pageTitle={translate.translate('passwordSetupTitle')}
            focusTargetId="password-setup-title"
          />
          <PageTitle headingId="password-setup-title">
            {translate.translate('passwordSetupTitle')}
          </PageTitle>
        </>
      }
    >
      {status === 'success' ? (
        <SuccessFeedback message={translate.translate('passwordSetupSuccess')} />
      ) : status === 'unknown' ? (
        <PersistentError title={translate.translate('passwordSetupUnknown')} />
      ) : !valid || status === 'failed' ? (
        <PersistentError title={translate.translate('passwordSetupUnavailable')} />
      ) : (
        <FormLayout
          ariaLabel={translate.translate('passwordSetupTitle')}
          onSubmit={(event) => {
            event.preventDefault();
            if (request.current !== undefined || challenge.current === undefined) return;
            const token = challenge.current;
            challenge.current = undefined;
            const newPassword = password;
            setPassword('');
            setPasswordRejected(false);
            setStatus('pending');
            const controller = new AbortController();
            request.current = controller;
            void runtime
              .establishPassword({ token, newPassword, signal: controller.signal })
              .then((result) => {
                if (controller.signal.aborted) return;
                request.current = undefined;
                if (
                  !result.ok &&
                  result.problem.status === 400 &&
                  [
                    'PASSWORD_TOO_SHORT',
                    'PASSWORD_TOO_LONG',
                    'PASSWORD_WHITESPACE_NOT_ALLOWED',
                    'PASSWORD_COMPROMISED',
                  ].includes(result.problem.code)
                ) {
                  challenge.current = token;
                  setPasswordRejected(true);
                  setStatus('ready');
                  return;
                }
                setStatus(
                  result.ok
                    ? 'success'
                    : result.problem.status === undefined || result.problem.status >= 500
                      ? 'unknown'
                      : 'failed',
                );
              });
          }}
        >
          <FormRow>
            <PasswordField
              id="password-setup-new-password"
              label={translate.translate('newPasswordLabel')}
              value={password}
              onValueChange={setPassword}
              autoComplete="new-password"
              error={passwordRejected ? translate.translate('passwordSetupPolicy') : undefined}
              required
              disabled={status === 'pending'}
            />
          </FormRow>
          <Button
            type="submit"
            variant="primary"
            loading={status === 'pending'}
            loadingLabel={translate.translate('passwordUpdateLoading')}
          >
            {translate.translate('passwordSetupTitle')}
          </Button>
        </FormLayout>
      )}
      <Button
        onClick={() => {
          challenge.current = undefined;
          void navigate('/login', { replace: true });
        }}
      >
        {translate.translate('signIn')}
      </Button>
    </PageLayout>
  );
}
